<a href="https://colab.research.google.com/github/AbdulWahabRaza123/ML/blob/main/BuildingInputPipeLines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
daily_sales_numbers=[21,22,-100,31,-1,32,34,31]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [6]:
for sales in tf_dataset:
  print(sales.numpy())

21
22
-100
31
-1
32
34
31


In [10]:
#or
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
-100
31
-1
32
34
31


In [12]:
#to show first 3 numbers
for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-100


In [13]:
#lets remove negative numbers
tf_dataset=tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
31
32
34
31


In [14]:
#lets convert these indian rupees into doller (1 doller=72)
tf_dataset=tf_dataset.map(lambda x:x*72)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1512
1584
2232
2304
2448
2232


In [18]:
#let's shuffle the elemenets with window of 3
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

2304
1512
2232
2232
1584
2448


In [20]:
#lets make batch (Group) of data
for sales_batch in tf_dataset.batch(2):
  print(sales_batch.numpy()) 

[2304 1512]
[2232 1584]
[2232 2448]


In [21]:
#we can do everything in a single line (which we do above)
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y:y*72).shuffle(3).batch(2)
for sales in tf_dataset:
  print(sales.numpy())

[1584 2304]
[2232 1512]
[2232 2448]


In [25]:
#reading images path
images_ds=tf.data.Dataset.list_files('/content/images/*/*',shuffle=False)

In [27]:
#showing images path
for file in images_ds.take(5):
  print(file.numpy())

b'/content/images/cat/download (10).jpg'
b'/content/images/cat/download (11).jpg'
b'/content/images/cat/download (12).jpg'
b'/content/images/cat/download (13).jpg'
b'/content/images/cat/download (2).jpg'


In [28]:
images_ds=images_ds.shuffle(200)
for file in images_ds.take(3):
  print(file.numpy())

b'/content/images/cat/download (12).jpg'
b'/content/images/cat/download (4).jpg'
b'/content/images/cat/download.jpg'


In [30]:
class_name=["cat","dog"]

In [31]:
image_count=len(images_ds)
image_count

25

In [32]:
#splitting train and test data
train_size=int(image_count*0.8) #80% trainning data
train_ds=images_ds.take(train_size) #train data
test_ds=images_ds.skip(train_size) #test data

In [33]:
len(train_ds)

20

In [34]:
len(test_ds)

5

In [39]:
s="/content/images/cat/download (12).jpg"
s.split("/")[-2]

'cat'

In [42]:
#getting label of images
def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[-2]

In [45]:
#readiing image from path
def process_image(file_path):
  label=get_label(file_path)
  img=tf.io.read_file(file_path)
  img=tf.image.decode_jpeg(img)
  img=tf.image.resize(img,[128,128])
  return img,label

In [41]:
#train_ds are file paths
for t in train_ds.take(4):
  print(t.numpy())

b'/content/images/cat/download (6).jpg'
b'/content/images/dog/download (5).jpg'
b'/content/images/cat/download (11).jpg'
b'/content/images/dog/download (9).jpg'


In [44]:
for label in train_ds.map(get_label):
  print(label.numpy())

b'dog'
b'dog'
b'dog'
b'dog'
b'cat'
b'cat'
b'cat'
b'dog'
b'dog'
b'cat'
b'cat'
b'dog'
b'cat'
b'cat'
b'cat'
b'dog'
b'cat'
b'cat'
b'dog'
b'cat'


In [48]:
train_ds=train_ds.map(process_image)
for img,label in train_ds.take(3):
  print("Image ",img)
  print("Label ",label)

Image  tf.Tensor(
[[[6.7000000e+01 2.7000000e+01 0.0000000e+00]
  [7.5718750e+01 3.6203125e+01 2.4218750e+00]
  [8.7812500e+01 4.8531250e+01 7.1093750e+00]
  ...
  [2.1614062e+02 2.3114062e+02 2.5214062e+02]
  [2.1548438e+02 2.3048438e+02 2.5148438e+02]
  [2.1500000e+02 2.3000000e+02 2.5100000e+02]]

 [[7.2859375e+01 3.4812500e+01 0.0000000e+00]
  [8.1105103e+01 4.3069580e+01 1.4758301e+00]
  [9.2283325e+01 5.4390625e+01 5.0189209e+00]
  ...
  [2.1711719e+02 2.3211719e+02 2.5311719e+02]
  [2.1646094e+02 2.3146094e+02 2.5246094e+02]
  [2.1597656e+02 2.3097656e+02 2.5197656e+02]]

 [[8.0687500e+01 4.6531250e+01 0.0000000e+00]
  [8.8456421e+01 5.4765625e+01 5.6762695e-02]
  [9.8846924e+01 6.5657104e+01 1.2751465e+00]
  ...
  [2.1714062e+02 2.3406250e+02 2.5410156e+02]
  [2.1648438e+02 2.3340625e+02 2.5344531e+02]
  [2.1600000e+02 2.3292188e+02 2.5296094e+02]]

 ...

 [[2.3296094e+02 2.4196094e+02 2.5500000e+02]
  [2.3247656e+02 2.4147656e+02 2.5500000e+02]
  [2.3195544e+02 2.4095544e+02 2

In [49]:
def scale(image,label):
  return image/255,label

In [50]:
train_ds=train_ds.map(scale)
for image,label in train_ds.take(5):
  print("Image is ",image[0][0])
  print("Label is ",label.numpy())

Image is  tf.Tensor([0.08627451 0.03137255 0.        ], shape=(3,), dtype=float32)
Label is  b'cat'
Image is  tf.Tensor([0.8276597  0.82373816 0.843346  ], shape=(3,), dtype=float32)
Label is  b'dog'
Image is  tf.Tensor([0.31029412 0.38088235 0.2240196 ], shape=(3,), dtype=float32)
Label is  b'dog'
Image is  tf.Tensor([0.9529412  0.8509804  0.03921569], shape=(3,), dtype=float32)
Label is  b'dog'
Image is  tf.Tensor([0.1064951 0.1182598 0.2944853], shape=(3,), dtype=float32)
Label is  b'dog'
